name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-linux:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        config: [ "01" , "02", "03", "04" ]
        compiler: [ "GNU", "Clang" ]
        script: [ "simple" ]


    steps:
    - uses: actions/checkout@v3
    - name: Update system
      run: sudo apt update
    - name: Install liburing
      run: sudo apt install -y liburing-dev
    - name: Install systemd
      run: sudo apt install -y libsystemd-dev
    - name: Install rst2man
      run: sudo apt install -y python3-docutils
    - name: Install zstd
      run: sudo apt install -y libzstd-dev
    - name: Install lz4
      run: sudo apt install -y liblz4-dev
    - name: Install bzip2
      run: sudo apt install -y libbz2-dev
    - name: Install graphviz
      run: sudo apt install -y graphviz
    - name: Install doxygen
      run: sudo apt install -y doxygen
    - name: Install clang
      run: sudo apt install -y clang
    - name: Install PostgreSQL
      run: |
        sudo apt install -y postgresql
        sudo apt install curl ca-certificates
        sudo install -d /usr/share/postgresql-common/pgdg
        sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
        sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        sudo apt update
        sudo apt install -y postgresql-17 postgresql-common postgresql-contrib
    - name: Set Env Path Variable
      run: |
        echo "PATH=$PATH:/usr/lib/postgresql/17/bin" >> $GITHUB_ENV

    - name: Run `simple` test for config ${{ matrix.config }}
      run: |
        chmod +x run
        ./run -C ${{ matrix.compiler }} -c ${{ matrix.config }} ${{ matrix.script }} 
      working-directory: /home/runner/work/pgagroal/pgagroal/tests

